### ISSUE TITLE
Finalize the application form fields and logic

### ISSUE THREAD

**Issue by samisa-abeysinghe** [Avinya-Foundation/admissions-application-frontend#2]
The following information must be finalized for the application form to be completed. 

1. What is the residence radius we are looking for? Eventually, we need the list of city IDs we allow the applicant to be able to apply from. Even if we are to use Google map APIs, we need the city IDs for data persistence of the applicant 
2. We need the finalized content text. "_By checking this box, I agree to the Terms of Use and Privacy Policy (unless I am under the age of 18, in which case, I represent that my parent or legal guardian also agrees to the Terms of Use on my behalf)_"
3. Can we have 3 sets of logic questions and not just 2. The plan is to have the questions in the DB as sets and play to the students and auto-mark based on the responses. This is based on a DB model and a data service. 
4. Can we move on to the essay section only if the student score more than 50% (or a similar %) for the logic section? 
5. Can we move on to the video section only if the two essays are good enough? 
6. What is the approach to auto-rate the essays? 
7. Can we provision that students submit the video only when they are for at a later stage? 
8. Can we assume that the email is the user ID for account creation? Email should be universally unique 
9. What are the application LC and states we want to show the student applicant on the application portal? 
10. What is the finalized list of education qualifications we need to capture? 
11. What is the  evaluation data model we want to use? 
12. What is the  qualification data model we want to use? 
13. What is the process for informing and inviting for interviews? What are the features we need from the portal for that? (That is part of the application LC)

**Comment by anjumoses** [comment]
1. I think we were looking at 30mins distance (car on google maps) - but I guess you need the cities/towns mapped for this? We can discuss today
2. Yes, let's do that today.
3. Agree to 3 sets of logic qs
4. Yes, that's a good idea
5. I think that will help with filtering and volume of videos to assess
6. We can discuss this today
7. Yes, agree
8. Yes, we can add a note regarding that
9.-13 - we can discuss today and add a finalised doc here.

**Comment by samisa-abeysinghe** [comment]
``` mermaid
flowchart TD
    A((Start))
    A-->B(Apply - register & create account) 
    B-->C(Provide learner profile information e.g education qualifications)
    C-->D(Take test 1 - logical test) 
    D-->F(Take test 2 - 2 essays of 150 words each)
    F-->I(Take test 3 - Record and upload reading of one of the essays)
    I-->J{Test 1 Markes good enough? && Test 2 Rating good enough? &&  Test 3 Video authorship verified?}
    J--No-->G(Set status to Pending)
    J--Yes-->K(Set status to Processing)
    
    K-->L(Process Application - by Aviya Foundation Evaluation Team)
    L-->M{Shortlited?}
    M--Yes-->N(Call for interview)
    M--No-->O(Set status to Rejected)
    G--Reconsider-->J
    G-->O
    N-->P{Pass Interview?}
    P--Yes-->Q(Set status to Selected)
    P--No-->O
    Q-->R(Send Offer)
    R-->S{Offer Accepted?}
    S--Yes-->T(Set status to Offer Accepted)
    S--No-->U(Set status to Offer Rejected)
    T-->V(Student Onboard)
    W((End))
     V-->W
     U-->W
     O-->W
```

**Comment by rukmal** [comment]
To answer some of the questions:
3. Yes
4. No, I think this fundamentally goes against our principle of holistically evaluating each student application.
5. No, same reason as #4
6. TBD; likely no for this round
7. No, we will need all information to make the interview/no interview decision

**Comment by rukmal** [comment]
@samisa-abeysinghe I don't think that we should be arbitrarily cutting off on a "pass mark" at all. A holistic application means that we evaluate the entire packet, so we shouldn't have a policy-level cutoff as such. We can build in filtering and sorting to the evaluation UI to streamline the process on our (admissions team) end.

**Comment by samisa-abeysinghe** [comment]
> To answer some of the questions: 3. Yes 4. No, I think this fundamentally goes against our principle of holistically evaluating each student application. 5. No, same reason as #4 6. TBD; likely no for this round 7. No, we will need all information to make the interview/no interview decision

Noted and updated the flowchart

**Comment by samisa-abeysinghe** [comment]
> @samisa-abeysinghe I don't think that we should be arbitrarily cutting off on a "pass mark" at all. A holistic application means that we evaluate the entire packet, so we shouldn't have a policy-level cutoff as such. We can build in filtering and sorting to the evaluation UI to streamline the process on our (admissions team) end.

Fixed in flowchart
